spring:
  application:
    name: "commerce"
  datasource:
    url: "jdbc:h2mem:testdb"
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.h2Dialect